# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["you@example.com"]
description = "Fastly Compute static site"
language = "javascript"
manifest_version = 2
name = "vite-starter"
service_id = "w7YyXX8isfSAp2j1bN5O21"

[scripts]
  build = "npm run build"
